listens for pdf and uploads to wiki
McMaster-Baja-Racing/BajaBot pull request #11
Opened 2024-10-23 20:13 UTC by hydrowoxy

Listens for pdfs in the #notes-and-stuff channel and automatically puts them on the wiki under the Meeting Minutes folder/page

2024-10-23 22:52 UTC, gr812b requested changes
A few nitpicks that could be addressed or ignored, and then I think adding the feedback to the user would be very beneficial and so requesting that pls 😍

2024-10-23 22:52 UTC, gr812b commented on events/pdf-listener.js
> +        if (message.channel.id === '1298058637121556612' && message.attachments.size > 0) { // Channel to listen in
Setting a const to `'1298058637121556612'` and giving it a descriptive name would make this easier to read. Could leave it as a global variable underneath imports

2024-10-23 22:52 UTC, gr812b commented on events/pdf-listener.js
> +                    formData.append('mediaUpload', JSON.stringify({ folderId: 17 }), { contentType: 'application/json' }); // 17 is meeting-minutes folder
Same as above, nitpicky but instead of comments, make a const

2024-10-23 22:52 UTC, gr812b commented on events/pdf-listener.js
> +                    console.error('Error processing PDF:', error.message);
Might be a nice idea to send a message that the document could not be uploaded inside the notes and stuff channel. Could even also add an ephemeral "Sucessfully made new page etc" message on success too as a reply

2024-10-23 22:52 UTC, gr812b commented on events/pdf-listener.js
> +                            }`
Nit: Prob not a bad idea to define this above for readability

2024-10-24 17:34 UTC, gr812b approved these changes
Looks great!

2024-10-24 17:43 UTC, hydrowoxy commented
yippee!!!

2024-10-24 17:43 UTC, merged